#!/bin/sh

pretty() {
	sed \
		-e '/^method return .*/d' \
		-e 's/^Error org.freedesktop.DBus.Error.Failed: "\?\(.*\)"\?$/ERROR: \1/' \
		-e 's/^   string "\(.*\)"/\1/' \
		-e 's/},/&\n/'
}

send() {
	dbus-send --system --print-reply \
		--dest=org.AGL.afm.system \
		/org/AGL/afm/system \
		org.AGL.afm.system.$1 \
		"string:$2" |
	pretty
}

case "$1" in

  add|install)
    f=$(realpath $2)
    send install '{"wgt":"'"$f"'","force":true}'
    ;;

  -h|--help|help)
    cat << EOC

The commands are:

  add wgt
  install wgt    install the wgt file

EOC
    ;;

  *)
    echo "unknown command $1" >&2
    exit 1
    ;;
esac


