#!/bin/sh

if [ -z "${XDG_RUNTIME_DIR+1}" ]; then
  export XDG_RUNTIME_DIR=/run/user/$UID
fi
LD_PRELOAD=/usr/lib/libEGL.so /usr/bin/qt5/qmlscene http://localhost:1234/opa /usr/share/agl/afb-viewer.qml

